# 3. 파이토치 기초

In [2]:
import torch

In [3]:
def print_val(x):
    print "Type:", type(x)
    print "Shape:", x.shape
    print "값:\n", x
    print " "

In [4]:
x = torch.rand(2,3,2) # uniform: 0~1 사이 모든 값들이 나올 확률이 같음
print_val(x)

x = torch.randn(2,3) # Gaussian: 0을 평균으로 하는 가우시안 분포를 따르는 랜덤값
print_val(x)

Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 3, 2])
값:
tensor([[[0.0747, 0.9868],
         [0.2518, 0.6072],
         [0.6270, 0.6666]],

        [[0.0628, 0.3619],
         [0.9277, 0.3480],
         [0.6708, 0.4776]]])
 
Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
값:
tensor([[ 0.1268,  0.9783, -0.1215],
        [ 0.6488,  0.9169,  1.1395]])
 


In [5]:
x = torch.randperm(4) # 0~ n-1 까지 값을 원소로 갖는 배열 -> 랜덤 배열
print_val(x)

Type: <class 'torch.Tensor'>
Shape: torch.Size([4])
값:
tensor([2, 3, 1, 0])
 


In [6]:
# [start, end) 구간을 step 단위로 나눠서 배열로 생성
x = torch.arange(0, 3, step=0.5)
print_val(x)

Type: <class 'torch.Tensor'>
Shape: torch.Size([6])
값:
tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])
 


In [7]:
print_val(torch.ones(3,4))
print_val(torch.zeros(3,4))

Type: <class 'torch.Tensor'>
Shape: torch.Size([3, 4])
값:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
 
Type: <class 'torch.Tensor'>
Shape: torch.Size([3, 4])
값:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
 


In [8]:
print_val(torch.Tensor(2,4))

Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 4])
값:
tensor([[-6.9467e-21,  4.5839e-41, -6.9467e-21,  4.5839e-41],
        [-4.0106e-01,  3.0946e-41, -5.0838e-21,  4.5839e-41]])
 


In [9]:
print_val(torch.Tensor([2,3]))

print_val(torch.Tensor([[2,3], [3,4]]))

Type: <class 'torch.Tensor'>
Shape: torch.Size([2])
값:
tensor([2., 3.])
 
Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 2])
값:
tensor([[2., 3.],
        [3., 4.]])
 


In [10]:
# 텐서 타입 변환
x = torch.FloatTensor(2,3)
print_val(x)

x = x.type_as(torch.IntTensor())
print_val(x)

Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
값:
tensor([[-5.1663e-21,  4.5839e-41, -5.1663e-21],
        [ 4.5839e-41, -5.1663e-21,  4.5839e-41]])
 
Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
값:
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
 


In [11]:
# 텐서 크기 반환
torch.FloatTensor(3,4,5).size()

torch.Size([3, 4, 5])

In [12]:
# numpy array -> torch tensor
import numpy as np
np_x = np.ndarray((2,3), dtype=int)
print_val(x)

x = torch.from_numpy(np_x)
print_val(x)

Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
값:
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
 
Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
값:
tensor([[140499621197928, 140499621197928, 140497497087936],
        [    25769803782,     25769803782,     25769803782]])
 
